
services:
  nginx:
    image: nginx:latest
    container_name: hotel_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_php
    volumes:
      - .:/var/www/html
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: hotel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_management
      MYSQL_USER: hotel_user
      MYSQL_PASSWORD: hotel_password
    volumes:
      - db_data:/var/lib/mysql
      - ./hotel_management.sql:/docker-entrypoint-initdb.d/hotel_management.sql
volumes:
  db_data:
